### PR TITLE
Set max length to 1

### PR DESCRIPTION
**Pull request by vinitkadam**
#27 
Set TextInput max length as 1

### CODE REVIEW

**Comment by dsznajder** [comment]
@vinitkadam Hi :) Does this work with copying? Because I've had an issue with that one and that's why I've left it untouched.

**Comment by vinitkadam** [comment]
what exactly do you mean by copying? It works as expected for me.

**Comment by dsznajder** [comment]
@vinitkadam Copy-pasting otp code, is working as expected?

**Comment by vinitkadam** [comment]
Yes. Copy-pasting otp code is working as expected.

**Pull request merged**
